import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

const myLoader = ({ src, width, quality }) => {
  return `${src}?w=${width}&q=${quality || 75}`;
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Star of th Moon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.title}>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 20 20"
            fill="#f5e942"
          >
            <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
          </svg>
          <h1>Star of the Month</h1>
        </div>
        <p className={styles.description}>
          Select your great teammate you enjoy working with!
        </p>
        <div className={styles.grid}>
          <div href="https://nextjs.org/docs" className={styles.card}>
            <Image
              loader={myLoader}
              src="https://airnfts.s3.amazonaws.com/profile-images/0xD9c4216cFE7c70344f80035B0bf5FBE01AA69d37_1619305985184.png"
              width="50rem"
              height="50rem"
              alt="profile-photo"
            />
            <p>Fatih Candan || Frontend Developer</p>
            <button className={styles.upstar}>
              <p>152</p>
              <div>Up Star</div>
            </button>
          </div>
          <div href="https://nextjs.org/docs" className={styles.card}>
            <Image
              loader={myLoader}
              src="https://airnfts.s3.amazonaws.com/profile-images/0xD9c4216cFE7c70344f80035B0bf5FBE01AA69d37_1619305985184.png"
              width="50rem"
              height="50rem"
              alt="profile-photo"
            />
            <p>Fatih Candan || Frontend Developer</p>
            <button className={styles.upstar}>
              <p>152</p>
              <div>Up Star</div>
            </button>
          </div>
          <div href="https://nextjs.org/docs" className={styles.card}>
            <Image
              loader={myLoader}
              src="https://airnfts.s3.amazonaws.com/profile-images/0xD9c4216cFE7c70344f80035B0bf5FBE01AA69d37_1619305985184.png"
              width="50rem"
              height="50rem"
              alt="profile-photo"
            />
            <p>Fatih Candan || Frontend Developer</p>
            <button className={styles.upstar}>
              <p>152</p>
              <div>Up Star</div>
            </button>
          </div>
          <div href="https://nextjs.org/docs" className={styles.card}>
            <Image
              loader={myLoader}
              src="https://airnfts.s3.amazonaws.com/profile-images/0xD9c4216cFE7c70344f80035B0bf5FBE01AA69d37_1619305985184.png"
              width="50rem"
              height="50rem"
              alt="profile-photo"
            />
            <p>Fatih Candan || Frontend Developer</p>
            <button className={styles.upstar}>
              <p>152</p>
              <div>Up Star</div>
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
